# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    remember-me:
      key: 77de3809bfd4f3b7d8a29db20587cb780c3a889aa85dfa61ea3b471c157bf7f1de3eb97844329a0008a70c774680c325abf0
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: LMS
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    password:
